import React from 'react'
import { useState, useContext } from 'react'
import {
  Box,
  Card,
  CardContent,
  Typography,
  useTheme,
} from "@mui/material";
import { AuthContext } from '../context/AuthContext'

const Help = () => {
  const { user } = useContext(AuthContext);
  const [activeKey, setActiveKey] = useState(null);
  const theme = useTheme();

  return (
    <>
      <Box p={3}>
        <Typography variant="h5" style={{
          border: "none",
          fontSize: "1.2rem",
          fontWeight: 'bold',
          marginBottom: "20px",
          color: theme.palette.text.main,
        }}>
          User Help Guide
        </Typography>
        <Card
          className="px-2 mt-2 mb-1"
          style={{
            minHeight: "400px",
            backgroundColor: theme.palette.background.paper,
            borderRadius: "8px",
            boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
          }}
        >
          <CardContent>
            <Box mb={2}>
              <Typography variant="subtitle1" gutterBottom style={{ color: theme.palette.text.primary, fontWeight: "bold", marginBottom: "10px" }}>
                Get the most out of SkyGuard by following these steps:
              </Typography>
              <ol style={{ paddingLeft: "1.2rem", lineHeight: "1.8", color: theme.palette.text.primary, fontSize: "12px" }}>
                <li>
                  <strong>Predict Your Future Flight Delay : </strong> Select your destination airport, Airline, Flight Scheduled Date and Time on Your dashboard. Then,
                  Click the Predict Delay button.
                </li>
                <li>
                  <strong>Understand Your Dashboard : </strong>Each prediction includes the delay probability, contributing factors, and operational insights generated by explainable AI. Review these narratives carefully to make informed travel or operational decisions. Also, you can Stay updated with aviation news relevant to your chosen airports. Summaries highlight critical events such as runway closures, strikes, or weather disruptions.
                </li>
                <li><strong>View your prediction History : </strong> All your past predictions are stored in the Report section so you can see predictions.
                </li><li><strong>Prediction Delay Email Alerts : </strong>If your flights might has high risk to delay, you will automatically receive an email notification with your prediction delay details.
                </li>
                <li>
                  <strong>Contact Support :</strong> If you encounter issues or have questions
                  about interpreting your results, our support team is available to assist.
                </li>
              </ol>
            </Box>

            <Box textAlign="center" mt={5}>
              <Typography style={{ color: theme.palette.text.main }}>
                Need additional help? Reach out to our support team:
              </Typography>

              <Typography color="info" style={{ color: theme.palette.text.primary }}>
                📞 <strong>Call Us :</strong> +94 77 123 4567 | +94 11 234 5678
              </Typography>

              <Typography color="info" style={{ color: theme.palette.text.primary }}>
                📧 <strong>Email :</strong>{" "}
                <a style={{ color: "#004d91ff" }} href="mailto:support@mashiama.com">support@skyguard.com </a>
              </Typography>
            </Box>
          </CardContent>
        </Card>
      </Box >
    </>
  )
}

export default Help
